### ISSUE TITLE
Thank you, suggestion and question(s)

### ISSUE THREAD

**Issue by dm82m** [erikkastelec/hass-WEM-Portal#1]
Hey @erikkastelec,

first of all - thank you! Due to missing time I only created a dirty way of using Wemportal in HA based on the work of another dev. See: https://github.com/dm82m/wemportal-scripts
I am currently testing out your integration and if that works well I will shut down my version and stay with yours! :)

I am running HA in a virtualenv and encountered the following log error after installing your component and a server restart:

```
Logger: homeassistant.components.homeassistant
Source: components/homeassistant/__init__.py:122
Integration: Home Assistant Core Integration (documentation, issues)
First occurred: 8:20:55 (1 occurrences)
Last logged: 8:20:55

Platform error sensor.wemportal - No module named 'scrapyscript'
```

So I manually installed scrapyscript with its dependencies in my virtualenv. Maybe you could put that as a hint in your readme.

I am also in contact with Weishaupt and they asked me to reduce the scan interval to 30mins due to server performance problems. But I will now run with your default and see what happens.

And one additional question: are you accessing the experts page to extract the data? If so, it is asking for a specialist code here on my Weishaupt gas heating system. I have not found this code '11 - in my case' in your script. So how do you access it?

Best,
Dirk

**Comment by erikkastelec** [comment]
Glad you like it. I will look into virtualenv install and if it is possible to make dependencies install by themselves. Otherwise, I will add the instructions to README.

Thank you for the info, I will increase the default and minimum scan intervals so the integration does not cause any issues for them.

The expert page loads the whole HTML before you enter the password, so I am scraping the sensor data without the need for a password.

**Comment by erikkastelec** [comment]
Home Assistant in virtualenv installs requirements by itself.  UI restart does not completely stop Home Assistant thus manual restart is required for this to work.
