### ISSUE TITLE
Forbidden Error 403

### ISSUE THREAD

**Issue by erikkastelec** [erikkastelec/hass-WEM-Portal#68]
As of today, May 5th, 2023, at 8:16 AM, it appears that Weishaupt has initiated IP bans. Consequently, I am unable to access the app or website from my home IP address.

If a resolution cannot be reached, it is likely that this component will need to be discontinued.

**Comment by dm82m** [comment]
That happend also in the past. If you restart your integration or the HA server to frequently there are too many requests made against wemportal and they are banning you. So it would be good to set it to 30mins… if you need the technical contact so that they can unban you, please contact me via mail dirk@maucher-online.de

**Comment by erikkastelec** [comment]
Great, first time for me. I will modify component restarts, so this does not happen to anyone else. I will probably just restart the modem to get a new IP, but thanks.

**Comment by dm82m** [comment]
Could it be an idea that we save the last request timestamp and ensure that we are not requesting again before current timestamp is greater than last request timestamp + scan_interval?

**Comment by erikkastelec** [comment]
Had the same idea. Should be easy to implement
