### ISSUE TITLE
HA UserWarning: Using slow pure-python SequenceMatcher.

### ISSUE THREAD

**Issue by iridium2001** [erikkastelec/hass-WEM-Portal#80]
In my logs, i found this message:

UserWarning: Using slow pure-python SequenceMatcher.

Logger: py.warnings
Source: custom_components/wemportal/wemportalapi.py:14
Integration: Weishaupt WEM Portal (documentation, issues)
First occurred: 00:24:27 (1 occurrences) [directly after a restart]
Last logged: 00:24:27

/usr/local/lib/python3.11/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

Aside of the message in the logs, there seems to be no practical issue associated with this. 
My current setup:

Home Assistant 2023.10.1
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231005.0 - latest

**Comment by erikkastelec** [comment]
Hi,

Nothing to worry about. The Python-Levenshtein package speeds up some operations we perform to combine data from our website and mobile app. These operations are quite infrequent, and I have decided to remove the package requirement due to some users experiencing issues with the package on Raspberry Pi devices.

Thanks for keeping an eye out for any bugs.
